name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  release:
    runs-on: windows-latest
    steps:
      - name: Checkout the source code
        uses: actions/checkout@v4

      - name: Setup python3
        uses: actions/setup-python@v5

      - name: Install requirements
        run: pip install -r requirements.txt

      - name: Clean the build script
        shell: pwsh
        run: |
          (Get-Content "build.bat" |
           Select-String -pattern "@echo off" -notmatch |
           Select-String -pattern "pause" -notmatch) |
          Set-Content "build.bat"

      - name: List build files
        run: |
          dir
          dir talon.dist
